local syntax = require "core.syntax"

syntax.add {
	files = { "%.bg$" },
	comment = "#",
	patterns = {
		{ pattern = "#.-\n",                  type = "comment" },
		{ pattern = { '"', '"', '\\' },       type = "string"  },
		{ pattern = { "'", "'" },             type = "number"  },
		{ pattern = "%d+",                    type = "number"  },
		{ pattern = "[%u_]+",                 type = "symbol"  },
		{ pattern = "[%+%-=/%*%^%%<>!|&%l]",  type = "symbol"  },
	},
	symbols = {
		["p"]       = "keyword",
		["s"]       = "keyword",
		["r"]       = "keyword",
		["+"]       = "keyword",
		["-"]       = "keyword",
		["*"]       = "keyword",
		["/"]       = "keyword",
		["%"]       = "keyword",
		["^"]       = "keyword",
		["c"]       = "keyword",
		["i"]       = "keyword",
		["t"]       = "keyword",
		["z"]       = "keyword",
		["y"]       = "keyword",
		["="]       = "keyword",
		["<"]       = "keyword",
		[">"]       = "keyword",
		["f"]       = "keyword2",
		["l"]       = "keyword2",
		["w"]       = "keyword",
		["e"]       = "keyword",
		["m"]       = "keyword",
		["o"]       = "keyword",
		["&"]       = "keyword",
		["|"]       = "keyword",
		["!"]       = "keyword2",
		["n"]       = "keyword",
		["d"]       = "keyword",
		["x"]       = "keyword",
		["h"]       = "keyword",
		["k"]       = "keyword",
		["a"]       = "keyword",
		["g"]       = "keyword",
		["q"]       = "keyword",
		["u"]       = "keyword",
		
		["BOING_VERSION"]                    = "literal",
		["BOING_VERSION_MAJOR"]              = "literal",
		["BOING_VERSION_MINOR"]              = "literal",
		["BOING_VERSION_REVISION"]           = "literal",
		["ARRAY"]                            = "literal",
		["NUMBER"]                           = "literal",
		["OPERATION"]                        = "literal",
		["EXTERNAL"]                         = "literal",
		["TRUE"]                             = "literal",
		["FALSE"]                            = "literal",
		["M_PI"]                             = "literal",
		["BOING_POOL_STRING_SIZE_GET"]       = "literal",
		["BOING_POOL_STRING_SIZE_SET"]       = "literal",
		["BOING_POOL_STRING_AMOUNT_GET"]     = "literal",
		["BOING_POOL_STRING_FREE_GET"]       = "literal",
		["BOING_POOL_STRING_MAX_FREE_GET"]   = "literal",
		["BOING_POOL_STRING_MAX_FREE_SET"]   = "literal",
		["BOING_POOL_ARRAY_SIZE_GET"]        = "literal",
		["BOING_POOL_ARRAY_SIZE_SET"]        = "literal",
		["BOING_POOL_ARRAY_AMOUNT_GET"]      = "literal",
		["BOING_POOL_ARRAY_FREE_GET"]        = "literal",
		["BOING_POOL_ARRAY_MAX_FREE_GET"]    = "literal",
		["BOING_POOL_ARRAY_MAX_FREE_SET"]    = "literal",
		["BOING_POOL_VALUE_SIZE_GET"]        = "literal",
		["BOING_POOL_VALUE_SIZE_SET"]        = "literal",
		["BOING_POOL_VALUE_AMOUNT_GET"]      = "literal",
		["BOING_POOL_VALUE_FREE_GET"]        = "literal",
		["BOING_POOL_VALUE_MAX_FREE_GET"]    = "literal",
		["BOING_POOL_VALUE_MAX_FREE_SET"]    = "literal",
		["SIN"]                              = "literal",
		["ASIN"]                             = "literal",
		["SINH"]                             = "literal",
		["COS"]                              = "literal",
		["ACOS"]                             = "literal",
		["COSH"]                             = "literal",
		["TAN"]                              = "literal",
		["ATAN"]                             = "literal",
		["TANH"]                             = "literal",
		["EXP"]                              = "literal",
		["LOG"]                              = "literal",
		["LOGTEN"]                           = "literal",
		["CEIL"]                             = "literal",
		["ABS"]                              = "literal",
		["FLOOR"]                            = "literal",
		["ATANTWO"]                          = "literal",
		["NULL"]                             = "literal",
	},
}